/**
 * exports graph into edge list in a form of array, where
 * each element has two items: [fromId, toId]
 */
module.exports = toEdgeList;

/**
 * exports graph into edge list in a string form, where each line
 * has two values fromId\ttoId
 */
module.exports.asString = asString;

/**
 * Exports graph into object with three properties:
 * + edgeList - array of edges
 * + edgeListString - string representation of the array (for quick export into a file)
 * + labels - array of labels
 * + labelsString - string representation of the labels (for quick export into a file)
 */
module.exports.asSet = asSet;

function toEdgeList(graph) {
  return toEdgeListInternal(graph);
}

function asString(graph) {
  var edgeList = toEdgeList(graph);
  return convertEdgeListToStr(graph, edgeList);
}

function asSet(graph) {
  var nodeIndex = Object.create(null);

  var edgeList = toEdgeListInternal(graph, nodeIndex);
  var edgeListStr =  convertEdgeListToStr(graph, edgeList);
  var labelsStr = convertLabelsToStr(nodeIndex);

  return {
    edgeList: edgeList,
    edgeListString: edgeListStr,
    labels: nodeIndex,
    labelsString : labelsStr
  };
}

function toEdgeListInternal(graph, nodeIndex) {
  nodeIndex = nodeIndex || Object.create(null);
  var last = 1;
  var edgeList = [];

  graph.forEachNode(mapToIndex);
  graph.forEachLink(save);

  return edgeList;

  function mapToIndex(node) {
    if (nodeIndex[node.id] === undefined) {
      nodeIndex[node.id] = last++;
    }
  }

  function save(link) {
    edgeList.push([nodeIndex[link.fromId], nodeIndex[link.toId]]);
  }
}


function convertEdgeListToStr(graph, edgeList) {
  var edgeListStr = [
    '# generated by ngraph.toedgelist',
    '# Nodes: ' + graph.getNodesCount(),
    '# Edges: ' + graph.getLinksCount(),
    '# FromId\tToId'
  ];
  for (var i = 0; i < edgeList.length; ++i) {
    var edge = edgeList[i];
    edgeListStr.push(edge[0] + '\t' + edge[1]);
  }

  return edgeListStr.join('\n');
}

function convertLabelsToStr(nodeIndex) {
  var labels = Object.keys(nodeIndex);

  var str = [
    '# generated by ngraph.toedgelist',
    '# NodeId\tLabel'
  ];

  for (var i = 0; i < labels.length; ++i) {
    var key = labels[i];
    str.push(nodeIndex[key] + '\t' + key);
  }

  return str.join('\n');
}
