/**
 * exports graph into edge list in a form of array, where
 * each element has two items: [fromId, toId]
 */
module.exports = toEdgesList;

/**
 * exports graph into edge list in a string form, where each line
 * has two values fromId\ttoId
 */
module.exports.asString = asString;

function toEdgesList(graph) {
  var nodeIndex = Object.create(null);
  var last = 1;
  var edgeList = [];

  graph.forEachNode(mapToIndex);
  graph.forEachLink(save);

  return edgeList;

  function mapToIndex(node) {
    if (nodeIndex[node.id] === undefined) {
      nodeIndex[node.id] = last++;
    }
  }

  function save(link) {
    edgeList.push([nodeIndex[link.fromId], nodeIndex[link.toId]]);
  }
}

function asString(graph) {
  var edgeList = toEdgesList(graph);
  var edgeListStr = [
    '# generated by ngraph.toedgeslist',
    '# Nodes: ' + graph.getNodesCount(),
    '# Edges: ' + graph.getLinksCount(),
    '# FromId\tToId'
  ];
  for (var i = 0; i < edgeList.length; ++i) {
    var edge = edgeList[i];
    edgeListStr.push(edge[0] + '\t' + edge[1]);
  }

  return edgeListStr.join('\n');
}
